# Kubernetes Secret Example
# Used to store sensitive information like passwords and tokens

apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: gitops-demo

type: Opaque

data:
  DB_USERNAME: ZGVtb3VzZXI=
  DB_PASSWORD: cGFzc3dvcmQxMjM=